---
- name: TP7
  hosts: all
  vars:
    temperature_csv_url: https://raw.githubusercontent.com/MrMegaNova/advanced_ansible_course_16_06/refs/heads/main/tp7/temperature.csv
    tmp_dest_csv_path: /tmp/temperature.csv

  tasks:
    - name: Download temperature CSV file
      ansible.builtin.get_url:
        url: "{{ temperature_csv_url }}"
        dest: "{{ tmp_dest_csv_path }}"
        mode: "0644"
        force: true

    - name: Read temperature CSV file
      community.general.read_csv:
        path: "{{ tmp_dest_csv_path }}"
      register: temperature_csv

    - name: Display temperature CSV content
      ansible.builtin.debug:
        var: temperature_csv.list
