all:
  hosts:
    10.0.0.79:
      packages:
        - apache2
        - mysql-server
    10.0.0.80:
      packages:
        - apache2
        - mysql-server
    10.0.0.81:
      packages:
        - git
        - nginx
        - cowsay
