---
- name: TP3
  hosts: all

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      become: true
      become_user: root
      when: packages is defined

    - name: Install ufw on Ubuntu machines only
      ansible.builtin.apt:
        name: ufw
        state: present
        update_cache: true
      become: true
      become_user: root
      when: ansible_facts["distribution"] == "Ubuntu"

    - name: Gather installed packages
      ansible.builtin.package_facts:
        manager: auto

    - name: Write index.html
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: "0644"
      become: true
      become_user: root
      when: "'apache2' in ansible_facts.packages or 'nginx' in ansible_facts.packages"
