---
galaxy_info:
  author: matheodrd
  description: Install wordpress

  license: MIT

  min_ansible_version: "2.18.6"

  galaxy_tags:
    - wordpress

dependencies:
  - role: geerlingguy.apache
  - role: geerlingguy.php
  - role: geerlingguy.apache-php-fpm
